# Generated by Django 4.1.3 on 2022-11-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Book tag',
                'verbose_name_plural': 'Book tags',
                'db_table': 'books_tags',
            },
        ),
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name ru')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name en')),
                ('name_alternative', models.CharField(max_length=255, verbose_name='Name alternative')),
                ('description', models.TextField(verbose_name='Description')),
                ('tags', models.ManyToManyField(related_name='titles', to='books.booktag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Book title',
                'verbose_name_plural': 'Book titles',
                'db_table': 'books_titles',
            },
        ),
        migrations.CreateModel(
            name='BookVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Volume name')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('number', models.PositiveIntegerField(verbose_name='Volume number')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='books.booktitle', verbose_name='Book title')),
            ],
            options={
                'verbose_name': 'Book volume',
                'verbose_name_plural': 'Book volumes',
                'db_table': 'books_volumes',
            },
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(verbose_name='Chapter number')),
                ('content', models.TextField(verbose_name='Chapter content')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Chapter views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Chapter likes')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.bookvolume', verbose_name='Book chapter')),
            ],
            options={
                'verbose_name': 'Book chapter',
                'verbose_name_plural': 'Book chapters',
                'db_table': 'books_chapters',
            },
        ),
        migrations.AddConstraint(
            model_name='bookvolume',
            constraint=models.UniqueConstraint(fields=('title', 'number'), name='unique_volume_for_title'),
        ),
        migrations.AddConstraint(
            model_name='bookchapter',
            constraint=models.UniqueConstraint(fields=('volume', 'number'), name='unique_chapter_for_volume'),
        ),
    ]
